
services:
  marketing:
    build: .
    container_name: marketing_api
    ports:
      - '${MARKETING_API_EXTERNAL_PORT}:8080'
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DB_NAME}?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USER_NAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_RABBITMQ_HOST: rabbitmq_service
      SPRING_RABBITMQ_PORT: 5672
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,metrics,prometheus
      MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: 'true'
    restart: always
    networks:
      - marketing_network

  mysql:
    image: mysql:8.0.33
    container_name: marketing_db
    environment:
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    networks:
      - marketing_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    restart: always
    ports:
      - '${PHPMYADMIN_EXTERNAL_PORT}:80'
    environment:
      PMA_HOST: mysql
    deploy:
      resources:
        reservations:
          cpus: '0.001'
          memory: 150M
    networks:
      - marketing_network

  rabbitmq_service:
    image: rabbitmq:4.0-rc-management
    container_name: rabbitmq_service
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - marketing_network

volumes:
  rabbitmq_data:
  rabbitmq_log:
  grafana-storage:

networks:
  marketing_network:
    driver: bridge
